In [1]:
## import json data from Data folder
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import jsonlines


# read the Training data
TrainData = []
with jsonlines.open('Data/clickbait17-train-170331/instances.jsonl') as reader:
    for obj in reader:
        TrainData.append(obj)
with jsonlines.open('Data/clickbait17-train-170630/instances.jsonl') as reader:
    for obj in reader:
        TrainData.append(obj)

TrainLabel = []
with jsonlines.open('Data/clickbait17-train-170331/truth.jsonl') as reader:
    for obj in reader:
        TrainLabel.append(obj)
with jsonlines.open('Data/clickbait17-train-170630/truth.jsonl') as reader:
    for obj in reader:
        TrainLabel.append(obj)
    

# read the Test data
TestData = []
TestLabel = []
with jsonlines.open('Data/clickbait17-test-170720/instances.jsonl') as reader:
    for obj in reader:
        TestData.append(obj)
with jsonlines.open('Data/clickbait17-test-170720/truth.jsonl') as reader:
    for obj in reader:
        TestLabel.append(obj)

In [2]:
df = pd.DataFrame(TrainData)
for index, row in df.iterrows():
    appendedTargetParagraphs = "".join(row["targetParagraphs"]) 
    df.at[index, "appendedTargetParagraphs"] = appendedTargetParagraphs

dfTrain = df[["targetTitle", "appendedTargetParagraphs"]]

dfTrain.head()

,targetTitle,appendedTargetParagraphs
0,Apple gives back gigabytes: iOS 9 'app thinnin...,Paying for a 64GB phone only to discover that ...
1,Emerging Markets Suffer Largest Outflow in Sev...,Emerging markets are out of favor.Global inves...
2,U.S. Soccer should start answering tough quest...,"WINNIPEG, Manitoba – The bubble U.S. Soccer is..."
3,How theme parks like Disney World left the mid...,When Walt Disney World opened in an Orlando sw...
4,Warning labels on your light bulbs,(CNN)The light bulb always makes the world's t...

In [3]:
dfLabels = pd.DataFrame(TrainLabel)
dfLabels = dfLabels[["truthClass"]]
dfLabels.replace({"truthClass": {"clickbait": 1, "no-clickbait": 0}}, inplace=True)
dfLabels.head()

dfTrain = pd.concat([dfTrain, dfLabels], axis=1)
dfTrain.head()

,targetTitle,appendedTargetParagraphs,truthClass
0,Apple gives back gigabytes: iOS 9 'app thinnin...,Paying for a 64GB phone only to discover that ...,0
1,Emerging Markets Suffer Largest Outflow in Sev...,Emerging markets are out of favor.Global inves...,0
2,U.S. Soccer should start answering tough quest...,"WINNIPEG, Manitoba – The bubble U.S. Soccer is...",1
3,How theme parks like Disney World left the mid...,When Walt Disney World opened in an Orlando sw...,0
4,Warning labels on your light bulbs,(CNN)The light bulb always makes the world's t...,1

In [4]:
## convert data to csv
dfTrain.to_csv("Data/ClickBaitTrain.csv", index=False)

In [6]:
df = pd.DataFrame(TestData)
for index, row in df.iterrows():
    appendedTargetParagraphs = "".join(row["targetParagraphs"]) 
    df.at[index, "appendedTargetParagraphs"] = appendedTargetParagraphs

dfTest = df[["targetTitle", "appendedTargetParagraphs"]]

dfTest.head()

,targetTitle,appendedTargetParagraphs
0,Johnny Manziel Says Top Pick in Draft Myles Ga...,Johnny Manziel approves of the Cleveland Brown...
1,Fabio: California Is a 'Mess' Because of Liber...,"Fabio, the Italian-born male model who has ado..."
2,"Jimmy Butler wants to return, hopes Bulls keep...",CHICAGO -- All-Star swingman Jimmy Butler know...
3,Mitchell Trubisky booed at United Center durin...,CHICAGO -- New Bears quarterback Mitchell Trub...
4,It's Not Enough to Give Employees Flexible Wor...,"Six months after her baby was born, Amanda San..."

In [7]:
dfLabels = pd.DataFrame(TestLabel)
dfLabels = dfLabels[["truthClass"]]
dfLabels.replace({"truthClass": {"clickbait": 1, "no-clickbait": 0}}, inplace=True)
dfLabels.head()

dfTest = pd.concat([dfTest, dfLabels], axis=1)
dfTest.head()

,targetTitle,appendedTargetParagraphs,truthClass
0,Johnny Manziel Says Top Pick in Draft Myles Ga...,Johnny Manziel approves of the Cleveland Brown...,0
1,Fabio: California Is a 'Mess' Because of Liber...,"Fabio, the Italian-born male model who has ado...",0
2,"Jimmy Butler wants to return, hopes Bulls keep...",CHICAGO -- All-Star swingman Jimmy Butler know...,1
3,Mitchell Trubisky booed at United Center durin...,CHICAGO -- New Bears quarterback Mitchell Trub...,0
4,It's Not Enough to Give Employees Flexible Wor...,"Six months after her baby was born, Amanda San...",0

In [8]:
dfTest.to_csv("Data/ClickBaitTest.csv", index=False)